apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.envFromSecret.secretName }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # These values will be provided during installation or through a CI/CD pipeline
  # The values here are placeholders and will be overridden
  OPENAI_API_KEY: {{ .Values.backend.secrets.openaiApiKey | default "" | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.password | default (randAlphaNum 16) | b64enc | quote }}
