apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded mongodb://username:password@hostname:port/
  # Replace with actual encoded connection string
  uri: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy8=
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # Replace with actual encoded API key
  api-key: eW91cl9vcGVuYWlfYXBpX2tleV9oZXJl
