apiVersion: v2
name: baseball-stats-dashboard
description: A Helm chart for the Baseball Stats Dashboard application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Ken Johansen
    email: kenney.johansen@gmail.com
    url: https://kenjohansen.dev
keywords:
  - baseball
  - statistics
  - dashboard
  - react
  - fastapi
  - kubernetes
home: https://github.com/kenjohansen/baseball-stats-dashboard
sources:
  - https://github.com/kenjohansen/baseball-stats-dashboard

# Dependencies
dependencies:
  - name: mongodb
    version: "~12.1.31"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.deploy
