# Default values for baseball-stats-dashboard
# This is a YAML-formatted file.

# Global settings
global:
  namespace: baseball-stats
  environment: production

# Frontend configuration
frontend:
  replicaCount: 2
  image:
    repository: kenjohansen/baseball-stats-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: baseball-stats.kenjohansen.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: baseball-stats-tls
        hosts:
          - baseball-stats.kenjohansen.dev

# Backend configuration
backend:
  replicaCount: 2
  image:
    repository: kenjohansen/baseball-stats-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi
  env:
    - name: DATABASE_NAME
      value: Baseball
    - name: COLLECTION_NAME
      value: Players
  envFromSecret:
    secretName: baseball-stats-secrets

# MongoDB configuration
mongodb:
  deploy: true  # Set to false to use external MongoDB
  external:
    uri: ""  # External MongoDB URI (e.g., "mongodb://user:password@mongodb.example.com:27017/Baseball?authSource=admin")
    secretName: ""  # Optional: Name of an existing secret containing MONGODB_URI
  auth:
    enabled: true
    rootPassword: ""  # Will be generated if not provided
    username: baseball
    password: ""  # Will be generated if not provided
    database: Baseball
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Prometheus monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
